# Generated by Django 6.1.1 on 2026-10-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='tipo de categoria')),
                ('descripcion', models.TextField(blank=True, default='placeholder', null=True, verbose_name='descripción del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre del producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('stock', models.IntegerField(verbose_name='cantidad en stock')),
                ('sku', models.IntegerField(verbose_name='codigo de referencia del producto')),
                ('fecha_ingreso', models.DateField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
        ),
    ]
